language: node_js
node_js:
  - stable

branches:
  except:
    - master

install:
  - npm install

deploy:
    - provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      file: public/bundle.js
      on:
        branch: master
